import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.or">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam
          sapiente ducimus sint sunt provident obcaecati numquam quisquam est!
          Dignissimos repellendus necessitatibus ad voluptatum harum deserunt
          minima nisi, commodi dolorum sunt.
        </p>
      </main>
    </>
  );
}
